In [1]:
import numpy as np

data1 = [6,7.5,8,0,9]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 9. ])

In [2]:
data2 = ([1,2,3,4],[4,6,7,9,])
arr2 = np.array(data2)
arr2,arr2.ndim,arr2.shape

(array([[1, 2, 3, 4],
        [4, 6, 7, 9]]), 2, (2, 4))

In [3]:
arr3 = np.zeros((3,7,5))
arr3

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [4]:
arr4 = np.empty((2,5))      #浮点数
arr4

array([[9.88131292e-324, 1.11749399e-311, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.11749399e-311, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])

In [5]:
arr5 = np.arange(0,17)      #0到16 左闭右开
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [6]:
arr6 = np.random.random(5)
arr6
arr6.shape,arr6.dtype        # (5,) float64  

((5,), dtype('float64'))

In [7]:
arr6.dtype = 'float32' 
arr6
arr6.shape,arr6.dtype        # (10,) float32


((10,), dtype('float32'))

In [8]:
arr6.dtype = 'float16' 
arr6
arr6.shape,arr6.dtype        # (20,) float16


((20,), dtype('float16'))

In [9]:
arr6.dtype = 'float' 
arr6
arr6.shape,arr6.dtype        # (5,) float64


((5,), dtype('float64'))

In [10]:
arr6.dtype = 'int64' 
arr6
arr6.shape,arr6.dtype        # (5,) int64    变成了无穷大


((5,), dtype('int64'))

In [12]:
arr7 = np.array([[1,2,3],[4,6,7]]    # ndarray 类型才可以进行数组乘法操作
# print(arr7 * arr7)                 # ipynb不可以进行数组乘法？
# arr7 - arr7
# 99*arr7
# 1/arr7
# arr7 ** 0.5

SyntaxError: invalid syntax (<ipython-input-12-f86feaab984d>, line 2)

In [15]:
arr8 = np.array([[1,2,3],[4,5,6],[7,8,9]])
# arr8[:2,1:]
# arr8[:,:1]
arr8[:,:1] = 0
arr8[:,:1]


array([[0],
       [0],
       [0]])