In [64]:
import numpy as np

In [65]:
arr1 = np.arange(9)

In [66]:
arr1[1::2]
# 每隔一个元素 从1开始

array([1, 3, 5, 7])

In [67]:
arr1[::-1]
# 逆序

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [68]:
arr2 = np.arange(20).reshape(4,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [69]:
arr2[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [70]:
arr2[:,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

In [71]:
arr2_sub = arr2[:2,:2]
arr2_sub

array([[0, 1],
       [5, 6]])

In [72]:
arr2_sub[0,0] = 99
# 默认非副本
arr2

array([[99,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [73]:
arr2_sub_copy = arr2[:2,:2].copy()
arr2_sub_copy[1,0] = 88
arr2


array([[99,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [76]:
arr3 = arr1.reshape((3,3))
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [83]:
arr4 = np.arange(1,4)
# arr4.reshape((1,3))   # 行
arr4.reshape((3,1))     # 列

array([[1],
       [2],
       [3]])

In [85]:
# arr4[np.newaxis,:]    # 行
arr4[,np.newaxis]       # 列

array([[1],
       [2],
       [3]])