In [3]:
import numpy as np

In [5]:
x = np.arange(1,6)

In [6]:
np.add.reduce(x)

15

In [8]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [9]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [9]:
data = ([3,5,7,9],[4,3,2,6],[6,7,3,5])
arr = np.array(data)
arr

array([[3, 5, 7, 9],
       [4, 3, 2, 6],
       [6, 7, 3, 5]])

In [ ]:
np.count_nonzero(arr)