In [3]:
import numpy as np
import pandas as pd

In [4]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [5]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           codes=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [6]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [7]:
pop[:,2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

#### 层级索引：低维表达高维

In [8]:
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [9]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [10]:
pop_df = pd.DataFrame({'total': pop,
                       'under18': [9267089, 9284094,
                                   4687374, 4318033,
                                   5906301, 6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [11]:
f_u18 = pop_df['under18'] / pop_df['total']
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [15]:
df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

data1     data2
a 1  0.240407  0.043952
  2  0.487344  0.736655
b 1  0.492300  0.744358
  2  0.963073  0.801060

In [16]:
pop.index.names = ['state', 'year']
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [17]:
# hierarchical indices and columns
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])

# mock some data
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data += 37

# create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      31.0  38.1  34.0  35.9  24.0  38.4
     2      41.0  37.8  34.0  36.7  33.0  37.2
2014 1      36.0  36.1  44.0  37.4  36.0  36.7
     2      41.0  36.2  46.0  37.6  40.0  37.1

In [18]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      34.0  35.9
     2      34.0  36.7
2014 1      44.0  37.4
     2      46.0  37.6

In [29]:

health_data.iloc[:2, :2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      31.0  38.1
     2      41.0  37.8

In [30]:
health_data.loc[:, ('Bob', 'HR')]

year  visit
2013  1        31.0
      2        41.0
2014  1        36.0
      2        41.0
Name: (Bob, HR), dtype: float64

In [31]:
idx = pd.IndexSlice
health_data.loc[idx[:, 1], idx[:, 'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      31.0  34.0  24.0
2014 1      36.0  44.0  36.0

In [26]:
data = np.round(np.random.randn(4, 6), 1)
data

array([[ 1.9, -0.6, -0.6,  0.2, -0. , -0.1],
       [-0.1,  0.6, -0.8,  1.1,  0.2,  2.4],
       [-2.2, -0.3,  0.8, -0.7, -0.8, -0.6],
       [ 1.5,  0.6,  1.3,  0.7,  2.4, -0.1]])

In [27]:
data[:, ::2] *= 10
data

array([[ 19. ,  -0.6,  -6. ,   0.2,  -0. ,  -0.1],
       [ -1. ,   0.6,  -8. ,   1.1,   2. ,   2.4],
       [-22. ,  -0.3,   8. ,  -0.7,  -8. ,  -0.6],
       [ 15. ,   0.6,  13. ,   0.7,  24. ,  -0.1]])

In [28]:
data += 37
data

array([[56. , 36.4, 31. , 37.2, 37. , 36.9],
       [36. , 37.6, 29. , 38.1, 39. , 39.4],
       [15. , 36.7, 45. , 36.3, 29. , 36.4],
       [52. , 37.6, 50. , 37.7, 61. , 36.9]])

In [32]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.236529
      2      0.996460
c     1      0.068926
      2      0.032569
b     1      0.126283
      2      0.661495
dtype: float64

In [33]:
try:
    data['a':'b']
except KeyError as e:
    print(type(e))
    print(e)

<class 'pandas.errors.UnsortedIndexError'>
'Key length (1) was greater than MultiIndex lexsort depth (0)'


In [ ]:
# sort_index
data = data.sort_index()
data

In [36]:
data = data.sort_index()
data

char  int
a     1      0.236529
      2      0.996460
b     1      0.126283
      2      0.661495
c     1      0.068926
      2      0.032569
dtype: float64