In [1]:
import numpy as np
import pandas as pd

In [2]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [3]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           codes=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [4]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [5]:
pop[:,2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

#### 层级索引：低维表达高维

In [6]:
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [7]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [8]:
pop_df = pd.DataFrame({'total': pop,
                       'under18': [9267089, 9284094,
                                   4687374, 4318033,
                                   5906301, 6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [9]:
f_u18 = pop_df['under18'] / pop_df['total']
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [10]:
df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

data1     data2
a 1  0.423234  0.494043
  2  0.806896  0.083082
b 1  0.275799  0.648947
  2  0.645575  0.538651

In [11]:
pop.index.names = ['state', 'year']
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [12]:
# hierarchical indices and columns
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])

# mock some data
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data += 37

# create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      52.0  37.3  15.0  36.6  39.0  36.1
     2      62.0  35.8  27.0  38.0  44.0  35.9
2014 1      24.0  36.5  38.0  39.3  48.0  38.6
     2      27.0  37.5  31.0  37.4  45.0  38.6

In [13]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      15.0  36.6
     2      27.0  38.0
2014 1      38.0  39.3
     2      31.0  37.4

In [14]:

health_data.iloc[:2, :2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      52.0  37.3
     2      62.0  35.8

In [15]:
health_data.loc[:, ('Bob', 'HR')]

year  visit
2013  1        52.0
      2        62.0
2014  1        24.0
      2        27.0
Name: (Bob, HR), dtype: float64

In [16]:
idx = pd.IndexSlice
health_data.loc[idx[:, 1], idx[:, 'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      52.0  15.0  39.0
2014 1      24.0  38.0  48.0

In [17]:
data = np.round(np.random.randn(4, 6), 1)
data

array([[ 0.9,  0.3,  0.1, -0.5, -0.5,  0.4],
       [ 1.1, -0.6, -0.6, -0.2, -1.2,  0.2],
       [-1.1, -0.4,  0.9, -1.2,  1.3,  0.6],
       [ 1.3,  1. ,  0.7,  0.1,  1.5, -0.3]])

In [18]:
data[:, ::2] *= 10
data

array([[  9. ,   0.3,   1. ,  -0.5,  -5. ,   0.4],
       [ 11. ,  -0.6,  -6. ,  -0.2, -12. ,   0.2],
       [-11. ,  -0.4,   9. ,  -1.2,  13. ,   0.6],
       [ 13. ,   1. ,   7. ,   0.1,  15. ,  -0.3]])

In [19]:
data += 37
data

array([[46. , 37.3, 38. , 36.5, 32. , 37.4],
       [48. , 36.4, 31. , 36.8, 25. , 37.2],
       [26. , 36.6, 46. , 35.8, 50. , 37.6],
       [50. , 38. , 44. , 37.1, 52. , 36.7]])

In [20]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.843324
      2      0.484735
c     1      0.139276
      2      0.725616
b     1      0.771878
      2      0.882836
dtype: float64

In [21]:
try:
    data['a':'b']
except KeyError as e:
    print(type(e))
    print(e)

<class 'pandas.errors.UnsortedIndexError'>
'Key length (1) was greater than MultiIndex lexsort depth (0)'


In [22]:
# sort_index
data = data.sort_index()
data

char  int
a     1      0.843324
      2      0.484735
b     1      0.771878
      2      0.882836
c     1      0.139276
      2      0.725616
dtype: float64

In [23]:
data = data.sort_index()
data

char  int
a     1      0.843324
      2      0.484735
b     1      0.771878
      2      0.882836
c     1      0.139276
      2      0.725616
dtype: float64

In [24]:
pop.unstack(level=0)

state  California  New York     Texas
year                                 
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561

In [25]:
pop.unstack(level=1)

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [35]:
pop.unstack().stack()

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [34]:
# 行列标签转换
pop_flat = pop.reset_index(name='population')
pop_flat

state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [36]:
pop_flat.set_index(['state', 'year'])

population
state      year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561