In [37]:
import numpy as np
import pandas as pd

In [38]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [39]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           codes=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [40]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [41]:
pop[:,2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

#### 层级索引：低维表达高维

In [42]:
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [43]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [44]:
pop_df = pd.DataFrame({'total': pop,
                       'under18': [9267089, 9284094,
                                   4687374, 4318033,
                                   5906301, 6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [45]:
f_u18 = pop_df['under18'] / pop_df['total']
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [46]:
df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

data1     data2
a 1  0.234287  0.503670
  2  0.587844  0.811040
b 1  0.453832  0.514905
  2  0.897361  0.118107

In [47]:
pop.index.names = ['state', 'year']
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [48]:
# hierarchical indices and columns
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])

# mock some data
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data += 37

# create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      27.0  36.3  35.0  38.6  38.0  38.9
     2      49.0  35.4  41.0  37.3  25.0  34.9
2014 1      30.0  37.4  36.0  37.8  28.0  35.3
     2      43.0  37.8  36.0  37.5  47.0  38.6

In [49]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      35.0  38.6
     2      41.0  37.3
2014 1      36.0  37.8
     2      36.0  37.5

In [50]:

health_data.iloc[:2, :2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      27.0  36.3
     2      49.0  35.4

In [51]:
health_data.loc[:, ('Bob', 'HR')]

year  visit
2013  1        27.0
      2        49.0
2014  1        30.0
      2        43.0
Name: (Bob, HR), dtype: float64

In [52]:
idx = pd.IndexSlice
health_data.loc[idx[:, 1], idx[:, 'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      27.0  35.0  38.0
2014 1      30.0  36.0  28.0

In [53]:
data = np.round(np.random.randn(4, 6), 1)
data

array([[-0.5,  0.1,  0.1, -0.2, -0.7, -0.4],
       [ 1.6, -1.1,  0.5,  0.7, -0.2, -0. ],
       [ 1.4, -0.2,  0.2,  1. ,  2.5, -1.9],
       [ 1.1, -0. ,  1.2,  0.6,  0.9,  2. ]])

In [54]:
data[:, ::2] *= 10
data

array([[-5. ,  0.1,  1. , -0.2, -7. , -0.4],
       [16. , -1.1,  5. ,  0.7, -2. , -0. ],
       [14. , -0.2,  2. ,  1. , 25. , -1.9],
       [11. , -0. , 12. ,  0.6,  9. ,  2. ]])

In [55]:
data += 37
data

array([[32. , 37.1, 38. , 36.8, 30. , 36.6],
       [53. , 35.9, 42. , 37.7, 35. , 37. ],
       [51. , 36.8, 39. , 38. , 62. , 35.1],
       [48. , 37. , 49. , 37.6, 46. , 39. ]])

In [56]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.937798
      2      0.337440
c     1      0.201335
      2      0.024968
b     1      0.369883
      2      0.057305
dtype: float64

In [57]:
try:
    data['a':'b']
except KeyError as e:
    print(type(e))
    print(e)

<class 'pandas.errors.UnsortedIndexError'>
'Key length (1) was greater than MultiIndex lexsort depth (0)'


In [58]:
# sort_index
data = data.sort_index()
data

char  int
a     1      0.937798
      2      0.337440
b     1      0.369883
      2      0.057305
c     1      0.201335
      2      0.024968
dtype: float64

In [59]:
data = data.sort_index()
data

char  int
a     1      0.937798
      2      0.337440
b     1      0.369883
      2      0.057305
c     1      0.201335
      2      0.024968
dtype: float64

In [60]:
pop.unstack(level=0)

state  California  New York     Texas
year                                 
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561

In [61]:
pop.unstack(level=1)

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [62]:
pop.unstack().stack()

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [63]:
# 行列标签转换
pop_flat = pop.reset_index(name='population')
pop_flat

state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [64]:
pop_flat.set_index(['state', 'year'])

population
state      year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

In [65]:
health_data
data_mean = health_data.mean(level='year')
data_mean

subject   Bob        Guido          Sue       
type       HR   Temp    HR   Temp    HR   Temp
year                                          
2013     38.0  35.85  38.0  37.95  31.5  36.90
2014     36.5  37.60  36.0  37.65  37.5  36.95

In [66]:
data_mean.mean(axis=1, level='type')

type         HR  Temp
year                 
2013  35.833333  36.9
2014  36.666667  37.4